"""Configuration constants for the Activity Detection system."""

# Camera
CAMERA_INDEX = 0
CAMERA_WIDTH = 1920
CAMERA_HEIGHT = 1080
CAMERA_ASK_ON_STARTUP = True
CAMERA_SCAN_MAX_INDEX = 6

# YOLO object detection
YOLO_MODEL = "yolov8n.pt"  # nano model for real-time speed
YOLO_CONFIDENCE = 0.35
YOLO_IOU_THRESHOLD = 0.55

# AI lab showcase filtering
YOLO_ALLOWED_CLASSES = {
	"person",
	"laptop",
	"tv",
	"keyboard",
	"mouse",
	"chair",
	"cell phone",
}

YOLO_CLASS_CONFIDENCE = {
	"person": 0.40,
	"laptop": 0.55,
	"tv": 0.60,
	"keyboard": 0.50,
	"mouse": 0.55,
	"chair": 0.68,
	"cell phone": 0.60,
}

YOLO_CLASS_ALIASES = {
	"tv": "monitor",
	"cell phone": "phone",
}

# Class-specific geometric heuristics for lab scenes
CHAIR_MAX_ASPECT_RATIO = 1.20   # chairs are usually taller than wide
CHAIR_MIN_BOTTOM_RATIO = 0.45   # chair bottom should be near lower half of frame
MONITOR_MIN_ASPECT_RATIO = 1.10  # monitor/tv is usually wider than tall

# Filter tiny person detections that often become ghost IDs
YOLO_MIN_PERSON_HEIGHT = 100
YOLO_MIN_PERSON_AREA = 10000
PERSON_DUPLICATE_IOU = 0.65

# MediaPipe pose
POSE_MIN_DETECTION_CONF = 0.55
POSE_MIN_TRACKING_CONF = 0.55
POSE_MODEL_COMPLEXITY = 1  # 0=lite, 1=full, 2=heavy
LANDMARK_VISIBILITY_MIN = 0.35

# MediaPipe hand landmarks (for robust V-sign and hand mapping)
HAND_MIN_DETECTION_CONF = 0.45
HAND_MIN_TRACKING_CONF = 0.45

# MediaPipe face mesh (eyes/iris/lips and dense face features)
FACE_MESH_ENABLED = True
FACE_MESH_MIN_DETECTION_CONF = 0.45

# Centroid tracker
TRACKER_MAX_DISAPPEARED = 40  # frames before dropping an ID
TRACKER_MAX_DISTANCE = 120  # max pixel distance to associate
TRACKER_MIN_IOU_MATCH = 0.06
TRACKER_CONFIRM_FRAMES = 5  # must be seen this many frames before counted
TRACKER_SMOOTHING_ALPHA = 0.45

# Action detection thresholds
# Angles (degrees)
STANDING_KNEE_ANGLE_MIN = 160
STANDING_HIP_ANGLE_MIN = 152
STANDING_LEG_EXTENSION_RATIO_MIN = 2.05
SITTING_CHAIR_KNEE_ANGLE_MAX = 145
SITTING_CHAIR_KNEE_ANGLE_MIN = 55
SITTING_CHAIR_HIP_ANGLE_MIN = 50
SITTING_CHAIR_HIP_ANGLE_MAX = 165
SITTING_CHAIR_LEG_EXTENSION_RATIO_MAX = 2.40
SITTING_GROUND_HIP_RATIO = 0.82  # hip_y / frame_h threshold
STANDING_HIP_ABOVE_KNEE_MARGIN = 6
SITTING_GROUND_HIP_ANKLE_DIFF_MAX = 55
CHAIR_HIP_VERTICAL_NEAR_PIXELS = 95
CHAIR_HIP_HORIZONTAL_RATIO = 0.65

# Temporal stabilization
POSTURE_SWITCH_DELAY_SEC = 1.0
ACTION_SWITCH_DELAY_SEC = 0.45
POSTURE_HISTORY_FRAMES = 12

# Waving
WAVE_HAND_ABOVE_SHOULDER = True
WAVE_MOVEMENT_THRESHOLD = 14  # pixels of hand movement between frames
WAVE_HISTORY_FRAMES = 10
HELLO_MOVEMENT_RATIO = 0.10
HELLO_MIN_SWAY_RATIO = 0.22
HELLO_MIN_MOVES = 1
HELLO_MIN_DIRECTION_CHANGES = 1
HELLO_HAND_MARGIN_RATIO = 0.18

# Walking
WALK_HISTORY_FRAMES = 16
WALK_MIN_CENTER_SHIFT_RATIO = 0.35
WALK_MIN_PER_FRAME_SHIFT_RATIO = 0.03
WALK_MIN_PHASE_CHANGES = 2
WALK_MIN_ANKLE_SWING_RATIO = 0.18

# V-sign (pose-based approximation)
V_SIGN_REQUIRE_HAND_RAISED = False
V_SIGN_MIN_SPREAD_RATIO = 0.10
V_SIGN_MIN_FINGER_LIFT_RATIO = 0.03
V_SIGN_RING_PINKY_RELAX_RATIO = 0.025
V_SIGN_MAX_THUMB_TO_SPREAD_RATIO = 1.35
V_SIGN_MAX_FACE_DISTANCE_RATIO = 3.2

# Using phone
PHONE_HAND_FACE_DISTANCE = 80

# Using laptop
LAPTOP_PERSON_DISTANCE = 185

# Talking (head movement)
TALKING_ENABLED = False
TALK_MOVEMENT_THRESHOLD = 10
TALK_HISTORY_FRAMES = 15
TALK_MIN_MOVEMENTS = 10

# Skeleton and debug visualization
SKELETON_ENABLED = True
SKELETON_ALPHA = 0.55
SKELETON_LINE_THICKNESS_MIN = 1
SKELETON_LINE_THICKNESS_MAX = 4
SKELETON_POINT_RADIUS_MIN = 2
SKELETON_POINT_RADIUS_MAX = 6
SKELETON_SHOW_CONFIDENCE_TEXT = False
SKELETON_CONF_TEXT_MIN_VIS = 0.55

SKELETON_COLOR_UPPER = (50, 220, 90)  # green
SKELETON_COLOR_LOWER = (255, 120, 40)  # blue/orange contrast in BGR space
SKELETON_COLOR_FACE = (220, 220, 0)
SKELETON_COLOR_HAND = (255, 70, 180)
SKELETON_COLOR_FOOT = (255, 200, 0)
SKELETON_COLOR_EYE = (255, 230, 120)
SKELETON_COLOR_IRIS = (255, 255, 255)
SKELETON_COLOR_LIPS = (120, 110, 255)

FACE_FEATURES_DRAW = True
FACE_FEATURES_ALPHA = 0.75
FACE_FEATURE_POINT_RADIUS = 1
FACE_FEATURE_IRIS_RADIUS = 2

# UI rendering
# Colors (BGR format for OpenCV)
COLOR_STANDING = (0, 200, 0)
COLOR_SITTING = (200, 150, 0)
COLOR_GROUND = (0, 220, 220)
COLOR_DEFAULT = (200, 200, 200)
COLOR_OBJECT = (180, 120, 60)
COLOR_UNCONFIRMED_TRACK = (120, 120, 120)

COLOR_TOP_BAR = (40, 40, 40)
COLOR_BOTTOM_BAR = (30, 30, 30)
COLOR_TEXT_WHITE = (255, 255, 255)
COLOR_TEXT_ACCENT = (0, 220, 255)
COLOR_TEXT_GREEN = (0, 255, 100)
COLOR_TEXT_RED = (80, 80, 255)

# Debug toggles for AI lab demo
DEBUG_SHOW_POSTURE_DETAILS = False
DEBUG_SHOW_TRACK_STATUS = False

# Font
FONT_SCALE_LABEL = 0.75
FONT_SCALE_BAR = 0.55
FONT_THICKNESS = 2
BAR_HEIGHT = 48

# Window
WINDOW_NAME = "Activity Detection - Live Demo"

# Inference device selection
ASK_GPU_ON_STARTUP = True
GPU_DEFAULT_USE_CUDA = True
